services:
  mysql:
    image: mysql:8.0
    env_file: 
      - .env
    command: mysqld --default_time_zone="Asia/Ho_Chi_Minh" --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
